---
- name: Instalar MariaDB
  yum:
    name:
      - mariadb-server
      - mariadb
    state: present

- name: Habilitar y arrancar MariaDB
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Instalar dependencias para Ansible MySQL
  yum:
    name:
      - python3-PyMySQL
    state: present

- name: Configurar contraseña root (temporal para pruebas)
  mysql_user:
    name: root
    host_all: yes
    password: "root123"
    priv: "*.*:ALL"
    state: present
  login_unix_socket: /var/lib/mysql/mysql.sock
