---
- name: Install Remi repositories for PHP
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install yum-utils (required to manage repositories)
  yum:
    name: yum-utils
    state: present

- name: Enable Remi PHP 7.4 repository
  command: yum-config-manager --enable remi-php74
  args:
    warn: false

- name: Install PHP 7.4 and required modules
  yum:
    name:
      - php
      - php-mysql
      - php-fpm
      - php-cli
      - php-common
      - php-gd
      - php-mbstring
      - php-xml
    state: latest

- name: Configure PHP-FPM to work with Nginx
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Create PHP session directory
  file:
    path: /var/lib/php/session
    state: directory
    owner: nginx
    group: nginx
    mode: '0770'

- name: Enable and start PHP-FPM
  systemd:
    name: php-fpm
    enabled: yes
    state: started
